$('#nav_left').append("<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->"
+ "<div class='collapse navbar-collapse navbar-ex1-collapse'>"
+ "<ul class='nav navbar-nav side-nav'>"
+ "<li>"
+ "<a href='ControllerSocios'><i class='fa fa-fw fa-file'></i>Socios</a>"
+ "</li>"
+ "<li>"        
+ "<a href='ControllerAsociacion'><i class='fa fa-fw fa-dashboard'></i>Asociacion</a>"
    + "</li>"             
+ "<li>"
    + "<a href='ControllerProfile'><i class='fa fa-fw fa-dashboard'></i>Perfil</a>"
    + "</li>"             
    + "<li>"
    + "<a href='ControllerTablon'><i class='fa fa-fw fa-dashboard'></i>Tablón Anuncios</a>"
    + "</li>"
    + "<li>"
    + "<a href='ControllerInvitados'><i class='fa fa-fw fa-dashboard'></i>Invitados</a>"
    + "</li>"    
    + "<li>"
        + "<a href='main.jsp'><i class='fa fa-fw fa-dashboard'></i> Dashboard</a>"
            + "</li>"
        + "<li>"
        + "<a href='charts.jsp'><i class='fa fa-fw fa-bar-chart-o'></i> Charts</a>"
            + "</li>"
        + "<li>"
        + "<a href='tables.jsp'><i class='fa fa-fw fa-table'></i> Tables</a>"
            + "</li>"
        + "<li>"
        + "<a href='forms.jsp'><i class='fa fa-fw fa-edit'></i> Forms</a>"
            + "</li>"
        + "<li>"
        + "<a href='bootstrap-elements.jsp'><i class='fa fa-fw fa-desktop'></i> Bootstrap Elements</a>"
            + "</li>"
        + "<li>"
        + "<a href='bootstrap-grid.jsp'><i class='fa fa-fw fa-wrench'></i> Bootstrap Grid</a>"
            + "</li>"
        + "<li>"
        + "<a href='javascript:;' data-toggle='collapse' data-target='#demo'><i class='fa fa-fw fa-arrows-v'></i> Dropdown <i class='fa fa-fw fa-caret-down'></i></a>"
            + "<ul id='demo' class='collapse'>"
            + "<li>"
                + "<a href='#'>Dropdown Item</a>"
                    + "</li>"
                + "<li>"
                + "<a href='#'>Dropdown Item</a>"
                    + "</li>"
                + "</ul>"
            + "</li>"
        + "<li>"
        + "<a href='ControllerMain?oper=redirect&url=blank-page'><i class='fa fa-fw fa-file'></i> Blank Page</a>"
            + "</li>"                 
        + "</ul>"
    + "</div>"
+ "<!-- /.navbar-collapse -->"
+ "</nav>");