package bean;

// Generated 23-mar-2017 23:45:21 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Asociacion generated by hbm2java
 */
public class Asociacion implements java.io.Serializable {

	private Integer idAsociacion;
	private String nombre;
	private String descripcion;
	private Date fechaFundacion;

	public Asociacion() {
	}

	public Asociacion(String nombre, String descripcion, Date fechaFundacion) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.fechaFundacion = fechaFundacion;
	}

	public Integer getIdAsociacion() {
		return this.idAsociacion;
	}

	public void setIdAsociacion(Integer idAsociacion) {
		this.idAsociacion = idAsociacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaFundacion() {
		return this.fechaFundacion;
	}

	public void setFechaFundacion(Date fechaFundacion) {
		this.fechaFundacion = fechaFundacion;
	}

}
