package bean;

// Generated 13-feb-2018 19:37:19 by Hibernate Tools 3.4.0.CR1

/**
 * Cuota generated by hbm2java
 */
public class Cuota implements java.io.Serializable {

	private Integer idCuota;
	private int tipoCuota;
	private String descripcion;

	public Cuota() {
	}

	public Cuota(int tipoCuota, String descripcion) {
		this.tipoCuota = tipoCuota;
		this.descripcion = descripcion;
	}

	public Integer getIdCuota() {
		return this.idCuota;
	}

	public void setIdCuota(Integer idCuota) {
		this.idCuota = idCuota;
	}

	public int getTipoCuota() {
		return this.tipoCuota;
	}

	public void setTipoCuota(int tipoCuota) {
		this.tipoCuota = tipoCuota;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
