package bean;

// Generated 22-abr-2017 18:44:50 by Hibernate Tools 3.4.0.CR1

/**
 * DesgloseCuentas generated by hbm2java
 */
public class DesgloseCuentas implements java.io.Serializable {

	private DesgloseCuentasId id;
	private int coste;
	private boolean pagado;

	public DesgloseCuentas() {
	}

	public DesgloseCuentas(DesgloseCuentasId id, int coste, boolean pagado) {
		this.id = id;
		this.coste = coste;
		this.pagado = pagado;
	}

	public DesgloseCuentasId getId() {
		return this.id;
	}

	public void setId(DesgloseCuentasId id) {
		this.id = id;
	}

	public int getCoste() {
		return this.coste;
	}

	public void setCoste(int coste) {
		this.coste = coste;
	}

	public boolean isPagado() {
		return this.pagado;
	}

	public void setPagado(boolean pagado) {
		this.pagado = pagado;
	}

}
