package bean;

// Generated 22-may-2017 22:53:39 by Hibernate Tools 3.4.0.CR1

/**
 * DesgloseCuentasAdicional generated by hbm2java
 */
public class DesgloseCuentasAdicional implements java.io.Serializable {

	private Integer idAdicional;
	private int idLibro;
	private int idPersona;
	private int annoCuenta;
	private int tipoCuota;
	private int cuotaAdicional;
	private boolean pagado;

	public DesgloseCuentasAdicional() {
	}

	public DesgloseCuentasAdicional(int idLibro, int idPersona, int annoCuenta,
			int tipoCuota, int cuotaAdicional, boolean pagado) {
		this.idLibro = idLibro;
		this.idPersona = idPersona;
		this.annoCuenta = annoCuenta;
		this.tipoCuota = tipoCuota;
		this.cuotaAdicional = cuotaAdicional;
		this.pagado = pagado;
	}

	public Integer getIdAdicional() {
		return this.idAdicional;
	}

	public void setIdAdicional(Integer idAdicional) {
		this.idAdicional = idAdicional;
	}

	public int getIdLibro() {
		return this.idLibro;
	}

	public void setIdLibro(int idLibro) {
		this.idLibro = idLibro;
	}

	public int getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}

	public int getAnnoCuenta() {
		return this.annoCuenta;
	}

	public void setAnnoCuenta(int annoCuenta) {
		this.annoCuenta = annoCuenta;
	}

	public int getTipoCuota() {
		return this.tipoCuota;
	}

	public void setTipoCuota(int tipoCuota) {
		this.tipoCuota = tipoCuota;
	}

	public int getCuotaAdicional() {
		return this.cuotaAdicional;
	}

	public void setCuotaAdicional(int cuotaAdicional) {
		this.cuotaAdicional = cuotaAdicional;
	}

	public boolean isPagado() {
		return this.pagado;
	}

	public void setPagado(boolean pagado) {
		this.pagado = pagado;
	}

}
