package bean;

// Generated 21-may-2018 21:52:38 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Invitado generated by hbm2java
 */
public class Invitado implements java.io.Serializable {

	private Integer idInvitado;
	private int idPersona;
	private Date fechaInvitacion;
	private String nombreInvitado;
	private String observaciones;
	private Date fechaCreate;
	private Date fechaDelete;

	public Invitado() {
	}

	public Invitado(int idPersona, Date fechaInvitacion, Date fechaCreate,
			Date fechaDelete) {
		this.idPersona = idPersona;
		this.fechaInvitacion = fechaInvitacion;
		this.fechaCreate = fechaCreate;
		this.fechaDelete = fechaDelete;
	}

	public Invitado(int idPersona, Date fechaInvitacion, String nombreInvitado,
			String observaciones, Date fechaCreate, Date fechaDelete) {
		this.idPersona = idPersona;
		this.fechaInvitacion = fechaInvitacion;
		this.nombreInvitado = nombreInvitado;
		this.observaciones = observaciones;
		this.fechaCreate = fechaCreate;
		this.fechaDelete = fechaDelete;
	}

	public Integer getIdInvitado() {
		return this.idInvitado;
	}

	public void setIdInvitado(Integer idInvitado) {
		this.idInvitado = idInvitado;
	}

	public int getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}

	public Date getFechaInvitacion() {
		return this.fechaInvitacion;
	}

	public void setFechaInvitacion(Date fechaInvitacion) {
		this.fechaInvitacion = fechaInvitacion;
	}

	public String getNombreInvitado() {
		return this.nombreInvitado;
	}

	public void setNombreInvitado(String nombreInvitado) {
		this.nombreInvitado = nombreInvitado;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Date getFechaCreate() {
		return this.fechaCreate;
	}

	public void setFechaCreate(Date fechaCreate) {
		this.fechaCreate = fechaCreate;
	}

	public Date getFechaDelete() {
		return this.fechaDelete;
	}

	public void setFechaDelete(Date fechaDelete) {
		this.fechaDelete = fechaDelete;
	}

}
