package bean;

// Generated 13-feb-2018 19:37:19 by Hibernate Tools 3.4.0.CR1

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

	private Integer idRol;
	private String nombre;
	private boolean activo;

	public Rol() {
	}

	public Rol(String nombre, boolean activo) {
		this.nombre = nombre;
		this.activo = activo;
	}

	public Integer getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Integer idRol) {
		this.idRol = idRol;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
