package bean;

// Generated 21-may-2018 21:52:38 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.security.auth.kerberos.ServicePermission;

import service.PersonaService;
import dao.PersonaDAO;

/**
 * TablonAnuncios generated by hbm2java
 */
public class TablonAnuncios implements java.io.Serializable {

	private Integer idAnuncio;
	private int idPersona;
	private String asunto;
	private String descripcion;
	private Date fechaCreate;
	private Date fechaDelete;
			
	public TablonAnuncios() {
	}

	/* No usar este constructor -> Es el generado de forma automatica por Hibernate */
	public TablonAnuncios(int idPersona, String asunto, String descripcion,
			Date fechaCreate, Date fechaDelete) {
		this.idPersona = idPersona;
		this.asunto = asunto;
		this.descripcion = descripcion;
		this.fechaCreate = fechaCreate;
		this.fechaDelete = fechaDelete;
	}
	
	public TablonAnuncios(Persona persona, String asunto, String descripcion,
			Date fechaCreate, Date fechaDelete) {
		this.idPersona = persona.getIdPersona();
		this.asunto = asunto;
		this.descripcion = descripcion;
		this.fechaCreate = fechaCreate;
		this.fechaDelete = fechaDelete;
	}

	public Integer getIdAnuncio() {
		return this.idAnuncio;
	}

	public void setIdAnuncio(Integer idAnuncio) {
		this.idAnuncio = idAnuncio;
	}

	public int getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}

	public String getAsunto() {
		return this.asunto;
	}

	public void setAsunto(String asunto) {
		this.asunto = asunto;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaCreate() {
		return this.fechaCreate;
	}

	public void setFechaCreate(Date fechaCreate) {
		this.fechaCreate = fechaCreate;
	}

	public Date getFechaDelete() {
		return this.fechaDelete;
	}

	public void setFechaDelete(Date fechaDelete) {
		this.fechaDelete = fechaDelete;
	}
	
	public Persona getPersona(){
		PersonaService serviceP = new PersonaService();
		return serviceP.getPersona(this.idPersona);
	}
}
