package bean;

// Generated 23-mar-2017 23:45:21 by Hibernate Tools 3.4.0.CR1

/**
 * TablonAnuncios generated by hbm2java
 */
public class TablonAnuncios implements java.io.Serializable {

	private Integer idAnuncio;
	private String emailPersona;
	private boolean activo;

	public TablonAnuncios() {
	}

	public TablonAnuncios(String emailPersona, boolean activo) {
		this.emailPersona = emailPersona;
		this.activo = activo;
	}

	public Integer getIdAnuncio() {
		return this.idAnuncio;
	}

	public void setIdAnuncio(Integer idAnuncio) {
		this.idAnuncio = idAnuncio;
	}

	public String getEmailPersona() {
		return this.emailPersona;
	}

	public void setEmailPersona(String emailPersona) {
		this.emailPersona = emailPersona;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
